### ISSUE TITLE
Releases are not built - Travis deployment bug

### ISSUE THREAD

**Issue by roborourke** [xwp/stream#1054]
# Bug Report

Looking at the Travis CI config it appears that the `deploy` section is intended to update the released tags on Github with the built version. Fetching the plugin via composer right now requires an additional build step.

```yml
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file: build/**/*
  on:
    tags: true

# Pull requests are built by default.
branches:
  only:
  - master
  - develop
```

The problem is that by using `branches: only` builds _only_ happen on these branches, tags are excluded so by setting `deploy: on: tags: true` this effectively means the deploy step can never run.

I would recommend either removing the `branches` section entirely or adding a regex to match your tag structure to that list.

## Expected Behavior

Travis should build and deploy when the repo is tagged.

## Actual Behavior

Travis does nothing, tag represents unbuilt commit.
